### ISSUE TITLE
redis_publish is always called if server.notes.redis is defined

### ISSUE THREAD

**Issue by smfreegard** [haraka/haraka-results#3]
I've just discovered that my spamtrap which uses Redis extensively and handles hundreds of connections a second is not performing as well as it could be because ResultStore is *always* running redis_publish if server.notes.redis is defined (defined by one of my plugins).

I only discovered this by accident when I ran 'MONITOR' on my Redis instance.

This should be configurable and **default to off**.   I believe this is solely used for the watch plugin, so watch should set a server note to enable this in ResultStore, or it could be enabled if someone wanted this in results.ini.

**Comment by msimerson** [comment]
> is not performing as well as it could be

I question whether this "problem" is real or one of perception. Have you tested disabling publish to see if it makes a detectable difference? And the results?

From [redis publish](https://redis.io/commands/publish):
> Time complexity: O(N+M) where N is the number of clients subscribed to the receiving channel and M is the total number of subscribed patterns (by any client).

M is always equals to 0 as the watch plugin only listens on the entire channel (earlier versions  used patterns), and if you don't have the watch plugin running, then N is also equal to 0. Meaning, the cost of the publish operation is roughly equivalent to firing a UDP packet onto the loopback interface.

**Comment by smfreegard** [comment]
> I question whether this "problem" is real or one of perception. Have you tested disabling publish to see if it makes a detectable difference? And the results?

Of course it's a problem and it makes a difference, I wouldn't have bothered writing a patch for it if not.

It's sending N bytes across a TCP connection for every plugin result and hardly requires a benchmark to know that this is unnecessary and bad if you don't need it.   M might be 0, but it still requires CPU time for Redis to read the command and discard it.

**Comment by msimerson** [comment]
closed by #4

**Comment by msimerson** [comment]
It [appears that plugin.server is not available](https://github.com/haraka/haraka-plugin-karma/issues/16) in NPM packaged plugins. That prevents this specific change from working with all published versions of Haraka.

**Comment by baudehlo** [comment]
So just access it from connection.server in the init function.

**Comment by msimerson** [comment]
> So just access it from connection.server in the init function.

That's one option. Another is to get plugin.server to exist. A third is adding an explicit setting to results.ini that toggles publishing. Whatever the solution, it should be tested before merging & publishing this time. Publishing broken versions of plugins caused at least 4 Haraka users to report problems with karma and/or watch. It's been broken until today when I had time to test the failures and find the underlying issue. Steve should either wait until someone else has time to test his changes or test them himself before self merging and publishing.

**Comment by smfreegard** [comment]
> Publishing broken versions of plugins caused at least 4 Haraka users to report problems with karma and/or watch. It's been broken until today when I had time to test the failures and find the underlying issue. Steve should either wait until someone else has time to test his changes or test them himself before self merging and publishing.

You might want to practice what you preach then.  

This is the first time I've caused you a bit of work and you've immediately just reverted all of my changes and then complained about it here.

If you want to be like that - the I can publicly state that you've caused me *hours* of work in the past with untested changes committed because you've re-factored code and they've affected far more than 4 users and caused plenty of people to pop-up on IRC.

I didn't just revert your changes, I spent the time answering questions on IRC and fixed them regardless - because I'm a team-player and bugs happen - none of us are perfect.

Like @baudehlo said - this was probably a one line change; but you don't want to do that do you?   You didn't agree with the changes in the first place, so you want to use the opportunity to do some dick waving and that is clear for anyone to see in this thread.

**Comment by msimerson** [comment]
> This is the first time I've caused you a bit of work

That's an amusing and forgetful assertion. It's also dismissive of the many hours I've spent tracking down, fixing, and writing tests for Haraka bugs.

> because I'm a team-player and bugs happen

"_smf_ I can bang out a fix if necessary - it just won't be tested ;-)"

That comment of yours sure demonstrates your team player attitude.

Yes, it's certainly true that I didn't like your "fix." I expected it to cause problems for Haraka users and it did. I suggested an alternative but you wouldn't hear of it. Rather than attempting to reach a consensus solution or even testing your proposal you rushed ahead. Since you don't use the affected plugins you chose to disrespect the author and users of it.

I still much prefer a config setting which toggles redis publishing off and on. It's dead simple to implement, dead simple to control, dead simple to troubleshoot, and unlike the @baudehlo suggestion, it won't ever suffer from race conditions where some results are never emitted because of plugin ordering.

**Comment by baudehlo** [comment]
I can't stand pissing matches like this and the conflict it creates.

I can see both sides to this argument. Nobody is completely right here. Try
and keep it civil, please.

However this gets solved is literally going to take a coin toss as either
solution will work. I tossed my coin towards make it magical last time but
I'm by no means 100% sold on that solution.

**Comment by smfreegard** [comment]
Thanks @baudehlo 

I've lost the will to work on this anymore.  I therefore don't care what fix goes in.  It certainly isn't going to be me working on it - that is for damn sure.

**Comment by msimerson** [comment]
closed by #10
